#!/usr/bin/env php
<?php

if (version_compare($ver = PHP_VERSION, $req = '5.4.0', '<')) {
    exit(sprintf("You are running PHP %s, but Pagekit needs at least PHP %s to run.\n", $ver, $req));
}

use Pagekit\Framework\Console\Application as Console;

if (PHP_SAPI != 'cli') {
	exit('Script needs to be run from Command Line Interface (cli)');
}

$app = require_once __DIR__.'/app/app.php';
$app->boot();

$console = new Console($app);
$console->run();